### PR TITLE
Russian localization

### PR DESCRIPTION
**Pull request by SerTheGreat**
Have created a Russian translation for SCANsat.
Haven't tested it in-game though, so community may want to make some changes to it. Also I haven't found any strings for button "Set" and for labels "Vessels", "Passes" and "Sensors", so I left references to them in English.
At least it's something to begin with.

If you find some strings are out of place feel free to replace any space with "\n" as Russian syntax allows that just like the English one does.

### CODE REVIEW

**Comment by DMagic1** [comment]
Excellent, thanks for these, I'll manually merge this in for the next version. 

I had to change a few things to get it working in 1.2.9, but otherwise it looks good, and SCANsat automatically detects language files that match the selected KSP language, so users won't need to do anything to activate it. 

The next update might not come until after the pre-release is over, though.

Also, I have a handful of other lines that will need translating, very short things like "start scan", or "analyze data" that you can hopefully help with. I'll need to get them finalized first, though.

**Comment by SerTheGreat** [comment]
If I don't respond on github feel free to PM me on KSP forums (Ser) and I'll try to help.
Have you thought about keeping languages in separate files to make it easier to see the diffs for the particular language?

**Comment by DMagic1** [comment]
SCANsat's existing localization method doesn't really support breaking up the strings into different files, and I don't want to deal with replacing the existing method with Squad's.

All of the other text that needs translating (science results, part descriptions, and the text I mentioned above, which is mostly the stuff that shows up in the part right-click menus) will be in separate files (three in total: parts, science, and other) and will use the standard stock localization methods.

All of this will be moved into a separate folder for localization.

**Comment by DMagic1** [comment]
In version 18 now. 

Many thanks.

**Pull request closed without merging**
