### PR TITLE
Experiment at integrating SCANsatRPM directly into SCANsat.

### PR DESCRIPTION
**Pull request by Mihara**
This isn't it yet, it needs some more work, but it should serve as a talking point and while I didn't test it, it should work, at least I think it compiles. :) You put the JSISCANsatRPM class directly into the main assembly and keep it there, and it will work identically.

There are several unsolved problems with this yet, two of which require fixing before this can be used:
- Quite a bit of code in SCANsatRPM actually duplicates existing SCANsat functionality even if it was rewritten from scratch, and this will need a lot more work to optimize correctly.
- The classes OrbitExtensions and CelestialBodyExtensions originate in MechJeb, and they're necessary to draw orbits. As such, I am not sure if their GPLv3 license is compatible with SCANsat, and it might need some negotiation, unless existing SCANsat functions can be adopted instead.
- SCANsatRPM needs to store several persistent variables, but cannot use the RPM's builtin mechanism to do it and not being a PartModule, can't do it the easy system way. Either you need to create your own method to do it, or I need to extend RPM API to somehow permit handlers to make use of it.

### CODE REVIEW

**Comment by DMagic1** [comment]
Am I understanding correctly that RPM stores all the relevant persistent variables (at least for SCANsatRPM) as a single string for each internal module, and that string is converted to a dictionary with the variable name and values?

Perhaps the scenario module could be used to the same effect. Do Internal modules have any kind of persistent, unique identifier (moduleID?) associated with them? Since we need to store variables for every potential screen we would need to have a method to store the variable name, the internal module identifier and the value; probably a nested dictionary would work if such an identifier exists.

**Comment by Mihara** [comment]
Yes, that's exactly what happens -- RPM serializes data into a string in the dumbest way. Initially I actually tried to make a scenario module to do the same thing globally, but by then I also realized that it's easier to make users add my module to part config anyway, so there's no point.

Internal modules have a chain of propID->moduleID that's always the same if you can uniquely identify the part, which was another reason why I abandoned that back then -- it was a pain to identify parts uniquely. After that it's just `internalModel.props[index_p].internalModules[index_m]`.

**Comment by DMagic1** [comment]
I can think of two ways the might work to get around this. SCANsat already has a method for tracking SCANsat-active vessels, so we could just make a vessel register as a SCANvessel whenever someone turns on an IVA map. Since we only need to store four variables we could probably just store them directly instead of using the dictionary thing. The only sticking point might be assigning a unique ID to each IVA on a single vessel.

The other method is to just go ahead and add the MapTraq module to everything with a ModuleCommand. This should cover everything with an IVA MFD right? Then we could just use a variation on the existing RPM method for persistent storage to record those four variables.

**Comment by Mihara** [comment]
You can reduce the load by adding MapTraq only to parts which have a RasterPropMonitorComputer module on them, but yeah, that would work too and would probably be quicker to code.

**Comment by DMagic1** [comment]
This seems to be working ok: a12176daa1cec09fe976b37fbd68505ba6b6032f. I just added a little helper class to store the handful of variables we need. Then I used the part module's OnSave() and OnLoad() to store and recover those variables for each prop.

As for the licensing issues, I think the entire project has to be released under GPLv3 if any one part of it is under that license. I suppose we might also just be able to get permission from Ramon, or Anatid, or whoever owns the license to use the class here. Only OrbitExtensions is needed, CelestialBodyExtensions just returns the terrain height, which is about half of what SCANsat does.

And as for code duplication, that's another problem. SCANsat has a lot of code scattered about in odd places that should really be put in a utilities class. The terrain height code and the orbital icons are two that I can think of right away that would affect SCANsatRPM.

**Pull request closed without merging**
