### PR TITLE
Update Science.cfg

### PR DESCRIPTION
**Pull request by AlejandroBaldwin**
Damm this took me more than I anticipated.. lol I have taken some artistic license to make some logical sense, because we all know straight translations aren't always logical. Specially with the Vall one :P I have made it be still a pun, so the people will still laugh, I guess lol

### CODE REVIEW

**Comment by DMagic1** [comment]
That's great, thanks for doing these. The science results definitely don't need to be literal translations.

I'll get all of these into the next update.

**Comment by DMagic1** [comment]
Just a few typos; peri genial to pero genial for Lo_Moho, and a few extra spaces.

**Comment by AlejandroBaldwin** [comment]
Oh crap, well I'm glad you noticed it. Sometimes the typos can slip away :/

**Comment by DMagic1** [comment]
In version 18 now. 

Many thanks.

**Pull request closed without merging**
