### PR TITLE
Chinese translation completed

### PR DESCRIPTION
**Pull request by Summerfirefly**

### CODE REVIEW

**Comment by DMagic1** [comment]
Thanks for these, everything looks good so far. I'm updating in just a minute with the translations you have.

I need to get an update out to fix a bug in the resource scanners, but there is no rush to finish the rest. 

And if you plan on doing the science results (there are a lot, so I would understand if you don't want to do them) don't worry about being too literal with the translations, those can be basically anything.

**Comment by Summerfirefly** [comment]
Thanks for your awesome work! And I'm one of Chinese QA volunteers, so I'll try my best to finish the rest when I have spare time. :) I hope it'll not be too late.

**Comment by haoliang968** [comment]
你好，请问如何快速的下载SCANsat？我在中国根本下载不下来。。。。

**Comment by Summerfirefly** [comment]
嗯。。下载是有点慢，要么挂个vpn，或者右键复制下载链接粘贴到迅雷里试试，有时候会快些

**Comment by DMagic1** [comment]
There are 13 more words in need of translating in the latest versions if you don't mind a little more work. These appear in the UI and so need to fit within the actual buttons. I can adjust the buttons if needed if there are problems with the text overflowing the space.

https://github.com/S-C-A-N/SCANsat/commit/3196f1b07541704dd43b9c65f417f0a680aba7fb

**Comment by Summerfirefly** [comment]
I've translated these words. :)

**Comment by DMagic1** [comment]
Great, thanks for these. These will probably be the last translations. A lot of the UI text is not very amenable to translation, and the KSPedia entry is just too much work.

**Comment by DMagic1** [comment]
In version 18 now. 

Many thanks.

**Pull request closed without merging**
